import type { Metadata } from "next";
import { AuroraOrb } from "@/components/ui";

export const metadata: Metadata = {
  title: "Terms of Service — VyAstro",
  description: "VyAstro Terms of Service. Please read these terms before using the VyAstro platform.",
};

const SECTIONS = [
  {
    title: "1. Acceptance of Terms",
    content: `By accessing or using VyAstro ("the Platform"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, please do not use the Platform.

These Terms constitute a legally binding agreement between you and VyAstro. We may update these Terms from time to time, and your continued use of the Platform following any changes constitutes acceptance of the updated Terms.`,
  },
  {
    title: "2. Nature of the Service",
    content: `VyAstro provides AI-powered astrological, Vastu, and Yantra guidance for informational, educational, and entertainment purposes.

**Important Disclaimers:**

- VyAstro's content is **not** a substitute for professional medical, legal, financial, psychological, or other professional advice
- Astrological and Vastu guidance is based on traditional Vedic systems and AI interpretation, and results may vary
- We make no guarantees about the accuracy, completeness, or specific outcomes of any reading, prediction, or recommendation
- The Platform is intended for adults (18+) who understand the nature of astrological guidance

Users acknowledge that any decisions made based on VyAstro's guidance are made at their own discretion and risk.`,
  },
  {
    title: "3. User Accounts and Waitlist",
    content: `When you join our waitlist or create an account, you agree to:

- Provide accurate and complete information
- Maintain the confidentiality of your account credentials
- Notify us immediately of any unauthorized access to your account
- Take responsibility for all activities that occur under your account

We reserve the right to terminate or suspend accounts that violate these Terms, engage in fraudulent activity, or compromise the security of other users.`,
  },
  {
    title: "4. Intellectual Property",
    content: `All content on the VyAstro Platform — including but not limited to text, graphics, logos, icons, images, audio, video, data compilations, and software — is the property of VyAstro or its content suppliers and is protected by applicable intellectual property laws.

You may not copy, reproduce, distribute, transmit, broadcast, display, sell, license, or otherwise exploit any content for commercial purposes without the prior written consent of VyAstro.

The ancient Vedic texts and wisdom underlying our platform are part of humanity's shared heritage. Our specific expressions, AI implementations, and platform design are proprietary.`,
  },
  {
    title: "5. Yantra Store Terms",
    content: `For purchases made through our Yantra Store (when available):

- All sales are final unless the product arrives damaged or defective
- Yantras are energized and consecrated products; their metaphysical efficacy is not guaranteed
- Descriptions of Yantra benefits are based on traditional Vedic texts and are not claims we can scientifically verify
- Delivery times vary by location; international shipping may be subject to customs duties for which the buyer is responsible
- We are not responsible for delays caused by customs, weather, or other factors outside our control`,
  },
  {
    title: "6. Prohibited Uses",
    content: `You agree not to use the Platform to:

- Violate any applicable law or regulation
- Transmit any harmful, offensive, or unlawful content
- Impersonate any person or entity
- Collect user data without consent
- Attempt to gain unauthorized access to the Platform
- Use the Platform for commercial purposes without authorization
- Reverse engineer or attempt to extract our AI models or proprietary algorithms
- Distribute or resell astrological reports generated by the Platform without our consent`,
  },
  {
    title: "7. Limitation of Liability",
    content: `To the maximum extent permitted by law, VyAstro and its officers, directors, employees, and agents shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from:

- Your use or inability to use the Platform
- Any decisions made based on Platform content
- Unauthorized access to your personal data
- Any errors or omissions in Platform content

Our total liability to you for any claims arising from use of the Platform shall not exceed the amount you paid to us in the 12 months preceding the claim.`,
  },
  {
    title: "8. Governing Law",
    content: `These Terms shall be governed by and construed in accordance with the laws of India, without regard to its conflict of law provisions. Any disputes arising from these Terms or your use of the Platform shall be subject to the exclusive jurisdiction of the courts located in India.

For users outside India, we comply with applicable local consumer protection laws to the extent required.`,
  },
  {
    title: "9. Contact",
    content: `For questions about these Terms, please contact us at:

**Email:** legal@vyastro.com
**Website:** vyastro.com/contact`,
  },
];

export default function TermsPage() {
  return (
    <div className="bg-cosmic-950 min-h-screen">
      <section className="relative pt-32 pb-16 overflow-hidden">
        <AuroraOrb size={400} top="0" left="40%" opacity={0.07} color="gold" />
        <div className="relative z-10 max-w-3xl mx-auto px-4 text-center">
          <h1 className="font-display text-5xl font-semibold text-white mb-4">Terms of Service</h1>
          <p className="text-white/40 text-sm">Last updated: January 1, 2025</p>
        </div>
      </section>

      <div className="max-w-3xl mx-auto px-4 sm:px-6 pb-24 space-y-6">
        <div className="glass rounded-2xl p-6 border border-gold-500/15">
          <p className="text-white/60 text-sm leading-relaxed">
            Please read these Terms of Service carefully before using VyAstro. These terms govern your access to and use of our platform, including our astrology, Vastu, AI guide, and Yantra store services.
          </p>
        </div>

        {SECTIONS.map(({ title, content }) => (
          <div key={title} className="glass rounded-2xl p-7 border border-white/5 space-y-4">
            <h2 className="font-display text-xl font-semibold text-white">{title}</h2>
            <div className="text-white/55 text-sm leading-relaxed space-y-3">
              {content.split("\n\n").map((para, i) => (
                <p key={i}>
                  {para.split("**").map((part, j) =>
                    j % 2 === 1 ? (
                      <strong key={j} className="text-white/80 font-semibold">
                        {part}
                      </strong>
                    ) : (
                      part
                    )
                  )}
                </p>
              ))}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
